config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
    get "login",  :to => "devise/sessions#create"
  end

  match "/browse" => "home#browse", via: :get
  match "/help" => 'home#help', via: :get
  match "/search" => "home#search", via: [:get, :post]

  root :to => "home#index"

  match "/recipes/random" => "recipes#random",  :via => :get, :as => :random_recipe

  resources :users, path: '' do
    member do
      post :follow
      post :unfollow
    end
    resources :recipes do
      resources :recipe_revisions, path: 'revisions', only: [:index, :show]
      member do
        get 'forks'
        post 'fork'
        get 'random'
        post 'star'
      end
    end
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_revisions

  has_many :events
  has_many :recipe_images
  has_many :forks, class_name: "Recipe", foreign_key: :forked_from_recipe_id
  has_many :revisions, class_name: "RecipeRevision"
  has_many :stars

  validates :commit_message, :presence => {:message => 'Update Message cannot be blank'}
  validates :title, :presence => {:message => 'Title cannot be blank'}

  validates_uniqueness_of :slug, :scope => :user_id

  include PgSearch

  multisearchable :against => [:title, :body]

  acts_as_taggable

  def forked_from
    Recipe.find(forked_from_recipe_id)
  end

  def to_param
    slug
  end

  def increment_revision!
    self.revision = self.revision + 1
  end

  def number_of_forks
    forks.count
  end

  def number_of_stars
    stars.count
  end

  def create_recipe_revision!
    RecipeRevision.create(:user           => user,
                          :title          => title,
                          :body           => body,
                          :commit_message => commit_message,
                          :recipe         => self,
                          :revision       => revision)
  end

  def valid_body?
    return true if RDiscount.new(body).to_html
  rescue
    false
  end

  def upload_images!
    images = self.body.scan(/!\[.*\]\((.*)\)/).flatten
    images.reject! { |i| i.include?('forkingrecipes') }
    images_to_recipe_images = images.map do |i|
      begin
        [i, RecipeImage.create!(:recipe => self, :image => open(i))]
      rescue
        nil
      end
    end.compact

    current_body = self.body

    images_to_recipe_images.each do |image_url, recipe_image|
      current_body = current_body.gsub(image_url, recipe_image.image.to_s)
    end

    self.update_attributes(:body => current_body)
  rescue
  end

  def fork_to(user)
    recipe = Recipe.new(:title => title,
                        :body => body,
                        :user => user,
                        :commit_message => "Forked From #{self.user.username}",
                        :slug => slug,
                        :forked_from_recipe_id => self.id,
                        :revision => 1)

    recipe.create_recipe_revision!

    return recipe
  end
end

app/models/recipe_revision.rb
class RecipeRevision < ActiveRecord::Base
  # attr_accessible :body, :commit_message, :revision, :title, :user, :recipe
  belongs_to :user
  belongs_to :recipe

  def previous
    RecipeRevision.where(recipe_id: recipe_id, revision: revision - 1).first if revision > 1
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include RecipesHelper
  include UsersHelper
  before_action :load_events, only: [:index]

  def index
    # redirect_to :landing if @events.empty?

    image_id_array = [549, 376, 529, 526]
    if image_id_array.all? {|image_id| RecipeImage.exists? image_id }
      recipe_images = RecipeImage.find image_id_array

      @images = recipe_images.map do |image|
        [image.image_url(:thumb), image.recipe]
      end
    else
      @images = []
    end
  end

  def search
    query = params[:query]
    results  = PgSearch.multisearch(query)
    @recipes = Recipe.where("id IN (?)", results.map(&:searchable_id))
  end

  def browse
    @recipes = Recipe.includes(:recipe_images).uniq(:slug).last(100).reverse
  end

  private

  def load_events
    if user_signed_in?
      followed_users = current_user.following
      @events = followed_users.map { |user| user.events.last(5) }.flatten.sort { |a, b| b.created_at <=> a.created_at }
    else
      @events = nil
    end
  end
end

app/controllers/recipe_revisions_controller.rb
class RecipeRevisionsController < ApplicationController
  include RecipesHelper
  before_filter :get_recipe
  before_filter :get_revision, only: [:show]

  def index
    @user             = @recipe.user
    @revisions        = RecipeRevision.where(recipe_id: @recipe.id)
    @recipe_permalink = @recipe.slug
  end

  def show
    @target_revision = if params[:target_id].present?
      RecipeRevision.find(params[:target_id])
    else
      @revision.previous
    end

    @diff = "Not Available" unless @target_revision.present?
    @diff ||= Differ.diff_by_line(@revision.body, @target_revision.body).format_as(:html).html_safe
  end

  private
  def get_revision
    @revision = RecipeRevision.find(params[:id])
  end

  def get_recipe
    @user = User.find_by_username(params[:user_id])
    @recipe = @user.recipes.find_by_slug(params[:recipe_id])
    return render inline: "We couldn't find that recipe in our system :(" unless @recipe
  end
end

app/views/home/browse.html.haml
%h3
  Featured Recipes
%section.featured
  = render @recipes

app/views/home/index.html.haml
%h3
  Featured Recipes
%section.featured
  - @images.each do |image, recipe|
    %div.rec-item
      %a.recipe-link{:href => recipe_path(recipe)}
        %img{:src => image}
        .item-text
          = recipe.title
      %ul.recipe-stats
        %li.forks
          %span.label
            %i.fa.fa-code-fork
            = pluralize(recipe.number_of_forks, 'fork')
        %li.saves
          %span.label
            %i.fa.fa-star
            = pluralize(recipe.number_of_stars, 'save')

%div.browse-more.action-btn
  = link_to('See More Recipes', browse_path)


- unless @events.blank?
  %div
    %h2 Recent Events
    %ul
      - @events.each do |event|
        %li= "#{link_to(event.user.username, user_path(event.user))} #{event.action} #{link_to(event.recipe.title, recipe_path(event.recipe))}".html_safe

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= @page_title || "ForkingRecipes"
    %meta{:content => "", :name => "description"}
    %meta{:content => "David Pick and Andy Standfield", :name => "author"}
    %link{:href => "//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,300,400,700|Merriweather:400,400italic,300italic,300,700,700italic|Source+Code+Pro", :rel => "stylesheet", :type => "text/css"}
    %link{:href=>"//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel=>"stylesheet"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{"data-controller" => controller_name, "data-action" => action_name}
    .navbar.navbar-fixed-top
      .navbar-inner
        = render 'layouts/navigation'
    - if controller_name == 'home' && action_name == 'index'
      = render 'layouts/welcome'
    #main{:role => "main"}
      %div{:id => "main-container"}
        .main-content
          = render 'layouts/messages'
          = yield
    %footer
      %aside{:style => "text-align: center;", :class=>"footer-info"}
        %a{:href => "mailto:forkingrecipes@gmail.com", :class=>"contact-link"}
          Contact Us
          %i.fa.fa-envelope

        %a{:href => "https://twitter.com/forkingrecipes", :target => "_blank"}
        %i.fa.fa-twitter-square.fa-3x
        %a{:href => "#", :target => "_blank"}
          %i.fa.fa-facebook-square.fa-3x
        %a{:href => "#", :target => "_blank"}
          %i.fa.fa-google-plus-square.fa-3x

        .copyright
          Copyright &copy; 2014,
          %a{:href => "https://twitter.com/forkingrecipes", :class=>"forking-recipes"}
            ForkingRecipes
            %i.fa.fa-twitter

    - if Rails.env == "production"
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-37615923-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

app/views/recipe_revisions/show.html.haml
- if @recipe.forked_from.present?
  %h2= "Forked from #{@recipe.forked_from.title}"
  - @recipe.forked_from.revisions.each do |rev|
    %span
      = link_to "#{rev.revision}", [@user, @recipe, @revision, target_id: rev.id]
- if @recipe.forks.present?
  %h2 Forks
  - @recipe.forks.each do |fork|
    %p= @recipe.title
    - fork.revisions.each do |rev|
      %span
        = link_to "#{rev.revision}", [@user, @recipe, @revision, target_id: rev.id]
%pre.diffs
  = @diff

app/views/recipes/_actions-menu.html.haml
%ul.actions
  - if current_user != @recipe.user
    %li
      = link_to fork_recipe_path(@recipe), :method => :post, :class => "action-btn" do
        %i.fa.fa-code-fork
        Fork

  - if !current_user.try(:following?, @recipe.user) && current_user != @recipe.user
    %li
      = link_to user_follow_path(@recipe.user), :class => "action-btn", :method => :post do
        %i.fa.fa-retweet
        Follow #{@recipe.user.username}

  - elsif current_user != @recipe.user
    %li
      = link_to user_unfollow_path(@recipe.user), :class => "action-btn", :method => :post do
        %i.fa.fa-retweet
        Unfollow #{@recipe.user.username}

  - if @recipe.revision > 1
    %li
      = link_to recipe_revisions_path(@recipe), :class => "action-btn", :id => "revisions_button" do
        %i.fa.fa-clock-o
        Revisions - #{@revision_count}

  - if current_user == @recipe.user
    %li
      = link_to edit_user_recipe_path(current_user, @recipe), :class => "action-btn" do
        %i.fa.fa-pencil
        Edit
    %li
      = link_to user_recipe_path(current_user, @recipe), :confirm => 'Are you sure you want to delete this recipe?', :method => :delete, :class => "action-btn btn-danger" do
        %i.fa.fa-trash-o
        Delete

  %li
    = link_to forks_path(@recipe), :class => 'action-btn' do
      %i.fa.fa-code-fork
      Forks - #{@forks}
  %li
    = link_to star_user_recipe_path(@recipe.user, @recipe), :method => 'post', :class => 'action-btn' do
      %i.fa.fa-paperclip
      Save to your recipes

- if @recipe.recipe_images.size > 0
  %ul.social-actions
    %li
      %a{:href => "//www.pinterest.com/pin/create/button/?url=#{request.original_url}&media=#{@recipe.recipe_images.last.image_url}&description=#{@recipe.title}", :'data-pin-do' => 'buttonPin', :'data-pin-config' => 'above'}
        <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" />
      <!-- Please call pinit.js only once per page -->
      <script type="text/javascript" async src="//assets.pinterest.com/js/pinit.js"></script>

app/views/recipes/_recipe.html.haml
%div.rec-item
  %a.recipe-link{:href => recipe_path(recipe)}
    %img{:src => recipe_thumbnail_path(recipe)}
    .item-text
      = recipe.title
  %ul.recipe-stats
    %li.forks
      %span.label
        %i.fa.fa-code-fork
        = pluralize(recipe.number_of_forks, 'fork')
    %li.saves
      %span.label
        %i.fa.fa-star
        = pluralize(recipe.number_of_stars, 'save')

app/views/users/show.html.haml
%ul.actions
  - if current_user && !current_user.following?(@user) && current_user != @user
    %li
      = link_to user_follow_path(@user), :class => "action-btn", :method => :post do
        %i.fa
        = "Follow #{@user.username}"
  - elsif current_user && current_user != @user
    %li
      = link_to user_unfollow_path(@user), :class => "action-btn", :method => :post do
        %i.fa
        = "Unfollow #{@user.username}"

- if !@recipes.empty?
  %div{:class => "recipes"}
    %table
      %tr
        %th.span5.recipe-header
          - if current_user == @user
            %h3 Your Recipes
          - else
            %h3= "#{@user.username}'s Recipes"
        %th.span5.recipe-header
          - if current_user == @user
            %h3 Your Favorited Recipes
      %tr
        %td.span5.recipe-list
          = render @recipes
        %td.span5.recipe-list
          - if current_user == @user
            = render @favorited_recipes

%br
%br
- if current_user
  = link_to "New Recipe", new_user_recipe_path(current_user), class: "action-btn"